### PR TITLE
Fix colored text and MessageComponent not being found

### LINKED ISSUE #567: Colored Text no longer works in latest update
Title says it all. I've tried restarting, reinstalling, pretty much every potential option to fix it on my end, but it seems more like a problem with BD itself.

### PR DESCRIPTION
**Pull request by jaimeadf**
Fixes #567 / #570 and `BDV2.MessageComponent` being `undefined` because of some internal changes on discord.

Thanks @Strencher for providing the fix for the `MessageComponent`.

### CODE REVIEW

**Comment by teixeira4** [comment]
@jaimeadf wait do u know a way how to fix colored text? If so, pls tell me

**Comment by Curtis-D** [comment]
@teixeira4 It's a pull request. The fix is literally in the commit above named "Fix colored text"

File: src/modules/v2.js [hunk 1]
```diff
@@ -100,7 +100,7 @@ export default new class V2 {
 	}
 
     get MessageContentComponent() {return this.WebpackModules.find(m => m.defaultProps && m.defaultProps.hasOwnProperty("disableButtons"));}
-    get MessageComponent() {return this.WebpackModules.find(m => m.default && m.default.displayName && m.default.displayName == "Message");}
+    get MessageComponent() {return this.WebpackModules.find(m => m.default?.toString().search('childrenRepliedMessage') > -1);}
```
Comment (Strencher) [inline src/modules/v2.js:103]: I would say, avoid simple chaining (`.?`) because it caused a lot issues for some users that doesn't have their discord client updated.

**Comment by teixeira4** [comment]
literally confused on how i fix it, could someone tell me in steps pls, im a bit slow

**Comment by Tropix126** [comment]
> literally confused on how i fix it, could someone tell me in steps pls, im a bit slow

Wait for this pull request to be merged.

**Comment by teixeira4** [comment]
oh kk, ty

File: src/modules/v2.js (hunk 1 above)
Comment (jaimeadf) [reply src/modules/v2.js]: Solved, I thought that everyone already used a version with support for ES6.

Comment (Strencher) [reply src/modules/v2.js]: that's what i thought too, but i keep seeing people having issues related to that in the support channels.

Comment (jaimeadf) [reply src/modules/v2.js]: I have just noticed that Babel is already transpiling to ES5 so it wouldn't cause any problems.

Comment (jaimeadf) [reply src/modules/v2.js]: Good that we fixed it though because now it's following the same code style.

**Comment by teixeira4** [comment]
oh, it's now merged

**Comment by teixeira4** [comment]
coloured text works for me now, I hat to install.
